2025-03-23 04:54:57,271 (7ddce8773808) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: a96edc6 (Fri Feb 21 14:37:39 UTC 2025)
2025-03-23 04:54:57,271 (7ddce8773808) :  DEBUG (core:361) - Using the elevated policy
2025-03-23 04:54:57,271 (7ddce8773808) :  DEBUG (core:450) - Starting runtime component.
2025-03-23 04:54:57,273 (7ddce8773808) :  DEBUG (core:450) - Starting caching component.
2025-03-23 04:54:57,273 (7ddce8773808) :  DEBUG (core:450) - Starting data component.
2025-03-23 04:54:57,273 (7ddce8773808) :  DEBUG (core:450) - Starting networking component.
2025-03-23 04:54:57,274 (7ddce8773808) :  DEBUG (networking:266) - No cookie jar found
2025-03-23 04:54:57,274 (7ddce8773808) :  DEBUG (networking:434) - Setting the default network timeout to 20.0
2025-03-23 04:54:57,275 (7ddce8773808) :  DEBUG (core:450) - Starting localization component.
2025-03-23 04:54:57,275 (7ddce8773808) :  INFO (localization:409) - Setting the default locale to en-us
2025-03-23 04:54:57,275 (7ddce8773808) :  DEBUG (core:450) - Starting messaging component.
2025-03-23 04:54:57,276 (7ddce535fb38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2025-03-23 04:54:57,277 (7ddce8773808) :  DEBUG (core:450) - Starting debugging component.
2025-03-23 04:54:57,277 (7ddce8773808) :  DEBUG (core:450) - Starting services component.
2025-03-23 04:54:57,278 (7ddce8773808) :  DEBUG (core:450) - Starting myplex component.
2025-03-23 04:54:57,278 (7ddce8773808) :  DEBUG (core:450) - Starting notifications component.
2025-03-23 04:54:57,684 (7ddce8773808) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2025-03-23 04:54:57,701 (7ddce8773808) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2025-03-23 04:54:57,732 (7ddce8773808) :  ERROR (networking:197) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2025-03-23 04:54:57,744 (7ddce8773808) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a96edc606/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a96edc606/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 243, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a96edc606/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 221, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a96edc606/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 159, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2025-03-23 04:54:57,762 (7ddce517eb38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2025-03-23 04:54:57,763 (7ddce517eb38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2025-03-23 04:54:57,763 (7ddce8773808) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2025-03-23 04:54:57,764 (7ddce5131b38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400'
2025-03-23 04:54:57,765 (7ddce8773808) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2025-03-23 04:54:57,765 (7ddce8773808) :  DEBUG (core:150) - Finished starting framework core
2025-03-23 04:54:57,765 (7ddce8773808) :  DEBUG (core:560) - Loading plug-in code
2025-03-23 04:54:57,847 (7ddce5131b38) :  DEBUG (core:538) - Machine identifier is 86237ceaf0dd4f14af393347c1370a88ca6e5a21
2025-03-23 04:54:57,847 (7ddce5131b38) :  DEBUG (core:539) - Server version is 1.41.5.9522-a96edc606
2025-03-23 04:54:57,935 (7ddce517eb38) :  DEBUG (services:362) - Loaded services
2025-03-23 04:54:57,953 (7ddce5154b38) :  DEBUG (services:438) - No shared code to load
2025-03-23 04:54:58,401 (7ddce8773808) :  DEBUG (core:566) - Finished loading plug-in code
2025-03-23 04:54:58,401 (7ddce8773808) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2025-03-23 04:54:58,402 (7ddce8773808) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2025-03-23 04:54:58,404 (7ddce8773808) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2025-03-23 04:55:18,093 (7ddce8773808) :  INFO (core:611) - Started plug-in
2025-03-23 04:55:18,094 (7ddce8773808) :  DEBUG (socketinterface:160) - Starting socket server
2025-03-23 04:55:18,095 (7ddce8773808) :  DEBUG (runtime:1117) - Created a thread named 'start'
2025-03-23 04:55:18,095 (7ddce8773808) :  INFO (socketinterface:184) - Socket server started on port 42347
2025-03-23 04:55:18,095 (7ddce8773808) :  INFO (pipeinterface:25) - Entering run loop
2025-03-23 04:55:18,095 (7ddce8773808) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2025-03-23 04:55:18,097 (7ddce8773808) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2025-03-23 04:55:18,098 (7ddce8773808) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2025-03-23 04:55:18,108 (7ddce4617b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2025-03-23 04:55:18,117 (7ddce45f0b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2025-03-23 04:55:18,127 (7ddce4617b38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a96edc606/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2025-03-23 04:55:18,127 (7ddce4617b38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2025-03-23 04:55:18,128 (7ddce4617b38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2025-03-23 04:55:18,129 (7ddce45f0b38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-a96edc606/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2025-03-23 04:55:18,129 (7ddce4617b38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2025-03-23 04:55:18,131 (7ddce45f0b38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2025-03-23 04:55:18,134 (7ddce45f0b38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2025-03-23 04:55:18,134 (7ddce45f0b38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
